### ISSUE TITLE
Support for schemars

### ISSUE THREAD

**Issue by frhuelsz** [TobiasDeBruijn/netplan-types#3]
Hi @TobiasDeBruijn. Thanks for this library. :)
We're thinking of using it as part of a project where the structs would be part of a larger struct where we're using [schema-rs](https://docs.rs/schemars/latest/schemars/) to automatically produce JSON Schema from the structs.

We were wondering if you'd be willing to take in this patch (or similar) to add optional support for schemars in netplan_types: https://github.com/TobiasDeBruijn/netplan-types/commit/8c692fee16d0ed89811cdabb18fe8bce8db0bab4

Thanks! :)

**Comment by TobiasDeBruijn** [comment]
Sure! Especially considering it's an optional feature, why not!

Could also be a good test for `netplan-types`, to compare the generated schema with the 'official' Netplan one (If it exists, though I believe it does).

Looking forward to a PR!
